on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  hello:
    runs-on: ubuntu-latest
      steps:
        env:
          world: hello world
      - uses: actions/checkout@v2
      - name: hello world
      run: echo ${{ env.world}}
      shell: bash
  goodbye:
    runs-on: ubuntu-latest
       steps:
        env:
          bye: goodbye world
      - name: goodbye world
        run: echo ${{ env.bye}}
        shell: bash
