on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        env:
          world: hello world
        run: echo ${{ env.world}}
        shell: bash
  #goodbye:
    #runs-on: ubuntu-latest
    #steps:
      #- name: goodbye world
    #env:
      #bye: goodbye world
      #run: echo ${{ env.bye}}
      #shell: bash
