on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  hello:
    runs-on: ubuntu-latest
    env:
      world: hello world
    steps:
    - uses: actions/checkout@v2
    - name: hello world
      run: echo ${{ env.world}}
      shell: bash
  goodbye:
    runs-on: ubuntu-latest
    env:
      bye: goodbye world
    steps:
      - name: goodbye world
        run: echo ${{ env.bye}}
        shell: bash
