on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: read a repo variable
      run: echo "My MY_APP_KEY value is ${{ vars.MY_APP_KEY}}

    - name: tell me a secret
      run: echo "My MY_SECRET_KEY value is ${{ secrets.MY_SECRET_KEY}}
      shell: bash
      
      
