on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  var1:
    runs-on: ubuntu-latest
    env: 
      MY_APP_KEY: ${{ secrets.MY_APP_KEY}}
    steps:
    - uses: actions/checkout@v2
    - name: read a repo variable
      run: echo "My MY_APP_KEY value is ${{ secrets.MY_APP_KEY}}
      shell: bash

  #var2:
    #runs-on: ubuntu-latest
    #steps:
    #- name: tell me a secret
      #run: echo "My MY_SECRET_KEY value is ${{ secrets.MY_SECRET_KEY}}
      #shell: bash
      
      
